"""Canonical taxonomy for electrical components and protocols."""

COMPONENT_TYPES = {
    "sensor",
    "plc_cpu",
    "plc_di",
    "plc_do",
    "plc_ai",
    "plc_ao",
    "power_supply",
    "circuit_breaker",
    "contactor",
    "thermal_overload",
    "vfd",
    "safety_relay",
    "terminal_block",
    "actuator",
    "communication_module",
    "hmi",
    "motor",
    "io_module",
    "servo_drive",
    "other",
    # Topology-specific types (used by topology generator / auto-connector)
    "plc",
    "safety_plc",
    "estop",
    "fuse",
    "disconnect",
    "transformer",
    "ipc",
    "switch",
    "relay",
    "power",
    "io",
    "servo",
    "safety_door",
    "signal_light",
    "indicator_light",
}

PROTOCOL_TYPES = {
    "PROFINET",
    "PROFIBUS",
    "ETHERCAT",
    "MODBUS",
    "ETHERNET",
    "CANOPEN",
    "IO_LINK",
    "SAFETY",
    "SAFETY_CIRCUIT",
    "POWER_24VDC",
    "POWER_24V",
    "POWER_AC",
    "POWER_220V",
    "SIGNAL",
    "UNKNOWN",
}
